### ISSUE TITLE
Include the itch.io link

### ISSUE THREAD

**Issue by dirkk0** [stealthio/Castle-Protection#8]
Great game!

You should include the itch.io link in this Github project!
https://scarred95.itch.io/castle-chess

Thanks, Dirk

**Comment by stealthio** [comment]
Good idea! Will do right now

**Comment by stealthio** [comment]
[Implemented](https://github.com/stealthio/Castle-Chess/commit/38dae38b5adc912e0573ffa7f22f64bc193341b8)
